---
title: "Lovisa och William"
# output: html_document
output:
  flexdashboard::flex_dashboard:
    theme:
      # united
      # simplex
      # yeti
      readable
        # primary:
          # "#144836"
    # logo:
      # example.svg
      
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(flexdashboard)
library(readxl)
library(leaflet)
library(DT)
library(htmltools)
```

Column {data-width=600}
--------------------------------------------------------------------------------
### 
```{r echo=FALSE}
loveData <- readxl::read_xlsx("data_points.xlsx")
loveData$Latitude <- as.numeric(loveData$Latitude)
loveData$Longitude <- as.numeric(loveData$Longitude)

scatterCoords <- function(inCoords, newCoords = c()) {
  curCoord <- as.character(inCoords[length(inCoords)])
  outCoords <- inCoords[-length(inCoords)]
  if(as.numeric(curCoord) %in% newCoords) {
    curCoord <- paste0(substr(curCoord, 1, 7), sample(0:9, 1))#, sample(0:9, 1))
  }
  if(length(outCoords) != 0) {
    scatterCoords(inCoords = outCoords, newCoords = c(as.numeric(curCoord), newCoords))
  } else {
    return(c(as.numeric(curCoord), newCoords))
  }
}

loveData$Latitude <- scatterCoords(loveData$Latitude)
loveData$Longitude <- scatterCoords(loveData$Longitude)

markerSettings <- awesomeIcons(icon = "heart", library = "fa", markerColor = "red", iconColor = "pink")

leaflet::leaflet(loveData, elementId = "myMap") %>%
  leaflet::addTiles() %>%
  leaflet::addAwesomeMarkers(lng = ~ Longitude, lat = ~ Latitude, label = ~ Händelse, popup = ~ paste0("<b>", Händelse, "</b>: ", Datum), icon = markerSettings) %>%
  htmlwidgets::onRender("
    function(el, x) {
      window.myNativeMap = this; 
    }
  ") # expose the map globally
```

Column {data-width=200}
--------------------------------------------------------------------------------
### 
```{r echo=FALSE}
# DT::datatable(data = loveData, extensions = "Select", selection = "none", rownames = FALSE, options = list(pageLength = 100, 
#     autoWidth = TRUE,
#     select = list(style = 'os', items = 'row'),
#     dom = "t",
#     columnDefs = list(list(visible = FALSE, targets = c(1, 2, 4)))
#   ), elementId = "myTable"
#   )

DT::datatable(
  data = loveData, 
  rownames = FALSE, 
  options = list(
    pageLength = 100, 
    dom = "t",
    autoWidth = TRUE,
    columnDefs = list(list(visible = FALSE, targets = c(2, 3, 4))),
    rowCallback = JS("
      function(row, data, index) {
        // data[0]=Händelse, data[1]=Datum, data[2]=Latitude, data[3]=Longitude
        $(row).attr('data-lat', data[2]);
        $(row).attr('data-lng', data[3]);
        $(row).attr('data-title', data[0]);
        $(row).attr('data-date', data[1]);
        $(row).css('cursor', 'pointer'); 
      }
    ") # store the data in the html
  ),
  callback = JS("
    // Listen for direct clicks on the table body rows
    table.on('click', 'tbody tr', function() {
      var row = $(this);
      var lat   = parseFloat(row.attr('data-lat'));
      var lng   = parseFloat(row.attr('data-lng'));
      var title = row.attr('data-title');
      var date  = row.attr('data-date');

      // Check if our global map instance has loaded and coordinates are valid numbers
      if (window.myNativeMap && !isNaN(lat) && !isNaN(lng)) {
        
        window.myNativeMap.closePopup();

        // Target the native Leaflet map engine directly to execute the panning camera 
        window.myNativeMap.flyTo([lat, lng], 15);

        // Render an interactive info popup window bubble
        L.popup()
          .setLatLng([lat, lng])
          .setContent('<strong>' + title + '</strong><br>' + date)
          .openOn(window.myNativeMap);
      }
    });
  ")
)
```
